name: 'kubectl-action'
description: 'Deploy to a Kubernetes cluster'
author: 'Daniel Richter'
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  kubeconfig:
    description: 'base64 encoded .kube/config'
  version:
    description: 'relase version'
  jobname:
    description: 'replace job name'
  namespace:
    description: 'name space'
    